<?php

namespace Proxies\__CG__\Proyecto\PrincipalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Espacio3 extends \Proyecto\PrincipalBundle\Entity\Espacio3 implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSuperficie($superficie)
    {
        $this->__load();
        return parent::setSuperficie($superficie);
    }

    public function getSuperficie()
    {
        $this->__load();
        return parent::getSuperficie();
    }

    public function setAnchoMinimoLibre($anchoMinimoLibre)
    {
        $this->__load();
        return parent::setAnchoMinimoLibre($anchoMinimoLibre);
    }

    public function getAnchoMinimoLibre()
    {
        $this->__load();
        return parent::getAnchoMinimoLibre();
    }

    public function setLargoMinimoLibre($largoMinimoLibre)
    {
        $this->__load();
        return parent::setLargoMinimoLibre($largoMinimoLibre);
    }

    public function getLargoMinimoLibre()
    {
        $this->__load();
        return parent::getLargoMinimoLibre();
    }

    public function setAlturaMinimaLibre($alturaMinimaLibre)
    {
        $this->__load();
        return parent::setAlturaMinimaLibre($alturaMinimaLibre);
    }

    public function getAlturaMinimaLibre()
    {
        $this->__load();
        return parent::getAlturaMinimaLibre();
    }

    public function setModoAula($modoAula)
    {
        $this->__load();
        return parent::setModoAula($modoAula);
    }

    public function getModoAula()
    {
        $this->__load();
        return parent::getModoAula();
    }

    public function setModoAulaCapacidad($modoAulaCapacidad)
    {
        $this->__load();
        return parent::setModoAulaCapacidad($modoAulaCapacidad);
    }

    public function getModoAulaCapacidad()
    {
        $this->__load();
        return parent::getModoAulaCapacidad();
    }

    public function setModoBanquete($modoBanquete)
    {
        $this->__load();
        return parent::setModoBanquete($modoBanquete);
    }

    public function getModoBanquete()
    {
        $this->__load();
        return parent::getModoBanquete();
    }

    public function setModoBanqueteCapacidad($modoBanqueteCapacidad)
    {
        $this->__load();
        return parent::setModoBanqueteCapacidad($modoBanqueteCapacidad);
    }

    public function getModoBanqueteCapacidad()
    {
        $this->__load();
        return parent::getModoBanqueteCapacidad();
    }

    public function setModoCocktail($modoCocktail)
    {
        $this->__load();
        return parent::setModoCocktail($modoCocktail);
    }

    public function getModoCocktail()
    {
        $this->__load();
        return parent::getModoCocktail();
    }

    public function setModoCocktailCapacidad($modoCocktailCapacidad)
    {
        $this->__load();
        return parent::setModoCocktailCapacidad($modoCocktailCapacidad);
    }

    public function getModoCocktailCapacidad()
    {
        $this->__load();
        return parent::getModoCocktailCapacidad();
    }

    public function setModoEscenario($modoEscenario)
    {
        $this->__load();
        return parent::setModoEscenario($modoEscenario);
    }

    public function getModoEscenario()
    {
        $this->__load();
        return parent::getModoEscenario();
    }

    public function setModoEscenarioCapacidad($modoEscenarioCapacidad)
    {
        $this->__load();
        return parent::setModoEscenarioCapacidad($modoEscenarioCapacidad);
    }

    public function getModoEscenarioCapacidad()
    {
        $this->__load();
        return parent::getModoEscenarioCapacidad();
    }

    public function setModoExposicion($modoExposicion)
    {
        $this->__load();
        return parent::setModoExposicion($modoExposicion);
    }

    public function getModoExposicion()
    {
        $this->__load();
        return parent::getModoExposicion();
    }

    public function setModoExposicionCapacidad($modoExposicionCapacidad)
    {
        $this->__load();
        return parent::setModoExposicionCapacidad($modoExposicionCapacidad);
    }

    public function getModoExposicionCapacidad()
    {
        $this->__load();
        return parent::getModoExposicionCapacidad();
    }

    public function setJardin($jardin)
    {
        $this->__load();
        return parent::setJardin($jardin);
    }

    public function getJardin()
    {
        $this->__load();
        return parent::getJardin();
    }

    public function setPilaresSueltos($pilaresSueltos)
    {
        $this->__load();
        return parent::setPilaresSueltos($pilaresSueltos);
    }

    public function getPilaresSueltos()
    {
        $this->__load();
        return parent::getPilaresSueltos();
    }

    public function setEntradaAseosMovilidadReducida($entradaAseosMovilidadReducida)
    {
        $this->__load();
        return parent::setEntradaAseosMovilidadReducida($entradaAseosMovilidadReducida);
    }

    public function getEntradaAseosMovilidadReducida()
    {
        $this->__load();
        return parent::getEntradaAseosMovilidadReducida();
    }

    public function setVentanasExterior($ventanasExterior)
    {
        $this->__load();
        return parent::setVentanasExterior($ventanasExterior);
    }

    public function getVentanasExterior()
    {
        $this->__load();
        return parent::getVentanasExterior();
    }

    public function setVentanasPatioInterior($ventanasPatioInterior)
    {
        $this->__load();
        return parent::setVentanasPatioInterior($ventanasPatioInterior);
    }

    public function getVentanasPatioInterior()
    {
        $this->__load();
        return parent::getVentanasPatioInterior();
    }

    public function setPosibilidadOscurecerSala($posibilidadOscurecerSala)
    {
        $this->__load();
        return parent::setPosibilidadOscurecerSala($posibilidadOscurecerSala);
    }

    public function getPosibilidadOscurecerSala()
    {
        $this->__load();
        return parent::getPosibilidadOscurecerSala();
    }

    public function setOtros($otros)
    {
        $this->__load();
        return parent::setOtros($otros);
    }

    public function getOtros()
    {
        $this->__load();
        return parent::getOtros();
    }

    public function setFechaRegistro($fechaRegistro)
    {
        $this->__load();
        return parent::setFechaRegistro($fechaRegistro);
    }

    public function getFechaRegistro()
    {
        $this->__load();
        return parent::getFechaRegistro();
    }

    public function setUser(\Proyecto\PrincipalBundle\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setEspacio2(\Proyecto\PrincipalBundle\Entity\Espacio2 $espacio2)
    {
        $this->__load();
        return parent::setEspacio2($espacio2);
    }

    public function getEspacio2()
    {
        $this->__load();
        return parent::getEspacio2();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'superficie', 'anchoMinimoLibre', 'largoMinimoLibre', 'alturaMinimaLibre', 'modoAula', 'modoAulaCapacidad', 'modoBanquete', 'modoBanqueteCapacidad', 'modoCocktail', 'modoCocktailCapacidad', 'modoEscenario', 'modoEscenarioCapacidad', 'modoExposicion', 'modoExposicionCapacidad', 'jardin', 'pilaresSueltos', 'entradaAseosMovilidadReducida', 'ventanasExterior', 'ventanasPatioInterior', 'posibilidadOscurecerSala', 'otros', 'fechaRegistro', 'user', 'espacio2');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}