<?php

namespace Proxies\__CG__\Proyecto\PrincipalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Localidad extends \Proyecto\PrincipalBundle\Entity\Localidad implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setSeo($seo)
    {
        $this->__load();
        return parent::setSeo($seo);
    }

    public function getSeo()
    {
        $this->__load();
        return parent::getSeo();
    }

    public function setLatitud($latitud)
    {
        $this->__load();
        return parent::setLatitud($latitud);
    }

    public function getLatitud()
    {
        $this->__load();
        return parent::getLatitud();
    }

    public function setLongitud($longitud)
    {
        $this->__load();
        return parent::setLongitud($longitud);
    }

    public function getLongitud()
    {
        $this->__load();
        return parent::getLongitud();
    }

    public function setPostal($postal)
    {
        $this->__load();
        return parent::setPostal($postal);
    }

    public function getPostal()
    {
        $this->__load();
        return parent::getPostal();
    }

    public function setProvincia(\Proyecto\PrincipalBundle\Entity\Provincia $provincia = NULL)
    {
        $this->__load();
        return parent::setProvincia($provincia);
    }

    public function getProvincia()
    {
        $this->__load();
        return parent::getProvincia();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'seo', 'postal', 'latitud', 'longitud', 'provincia');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}