<?php

namespace Proyecto\PrincipalBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UsersController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Proyecto\PrincipalBundle\Controller\UsersController();
        return $instance;
    }
}
