proyecto_principal_homepage:
    pattern:  /
    defaults: { _controller: ProyectoPrincipalBundle:Default:index }
proyecto_principal_eventos:
    pattern:  /eventos
    defaults: { _controller: ProyectoPrincipalBundle:Default:eventos }
proyecto_principal_evento:
    pattern:  /evento
    defaults: { _controller: ProyectoPrincipalBundle:Default:evento }



proyecto_principal_espacio:
    pattern:  /espacio
    defaults: { _controller: ProyectoPrincipalBundle:Default:espacio }
proyecto_principal_espacios:
    pattern:  /espacios
    defaults: { _controller: ProyectoPrincipalBundle:Default:espacios }
proyecto_principal_espacio_registrar:
    pattern:  /registrar/espacio
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:registrar }
proyecto_principal_espacio_editar:
    pattern:  /editar/espacio
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:editar }
proyecto_principal_espacio_registrar2:
    pattern:  /registrar/espacio/2
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:registrar2 }
proyecto_principal_espacio_editar2:
    pattern:  /editar/espacio/2
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:editar2 }
proyecto_principal_espacio_registrar3:
    pattern:  /registrar/espacio/3
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:registrar3 }
proyecto_principal_espacio_editar3:
    pattern:  /editar/espacio/3
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:editar3 }
proyecto_principal_espacio_registrar4:
    pattern:  /registrar/espacio/4
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:registrar4 }
proyecto_principal_espacio_editar4:
    pattern:  /editar/espacio/4
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:editar4 }
proyecto_principal_espacio_registrar5:
    pattern:  /registrar/espacio/5
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:registrar5 }
proyecto_principal_espacio_editar5:
    pattern:  /editar/espacio/5
    defaults: { _controller: ProyectoPrincipalBundle:Espacio:editar5 }

proyecto_principal_servicio:
    pattern:  /servicio
    defaults: { _controller: ProyectoPrincipalBundle:Default:servicio }
proyecto_principal_servicios:
    pattern:  /servicios
    defaults: { _controller: ProyectoPrincipalBundle:Default:servicios }
proyecto_principal_sedes:
    pattern:  /sedes
    defaults: { _controller: ProyectoPrincipalBundle:Default:sedes }


proyecto_users_buscar_ciudad:
    pattern:  /users/buscarCiudad
    defaults: { _controller: ProyectoPrincipalBundle:Users:buscarCiudad }
    requirements:
      _method: POST

proyecto_contacto_enviar_mensaje:
    pattern:  /contacto/enviarMensaje
    defaults: { _controller: ProyectoPrincipalBundle:Contacto:enviarMensaje}
    requirements:
      _method: POST

proyecto_perfil_privado:
    pattern:  /perfil/privado
    defaults: { _controller: ProyectoPrincipalBundle:Perfil:privado }
proyecto_perfil_publico:
    pattern:  /perfil/publico
    defaults: { _controller: ProyectoPrincipalBundle:Perfil:publico }
proyecto_perfil_editar:
    pattern:  /perfil/editar
    defaults: { _controller: ProyectoPrincipalBundle:Perfil:editar }
proyecto_perfil_crearcuenta:
    pattern:  /crearcuenta
    defaults: { _controller: ProyectoPrincipalBundle:Perfil:crearCuenta }
proyecto_perfil_facturacion:
    pattern:  /perfil/facturacion
    defaults: { _controller: ProyectoPrincipalBundle:Facturacion:index }
proyecto_perfil_enviar_solicitud_baja:
    pattern:  /perfil/enviarSolicitudBaja
    defaults: { _controller: ProyectoPrincipalBundle:Perfil:enviarSolicitudBaja }
    requirements:
      _method: POST
proyecto_perfil_cancelar_solicitud_baja:
    pattern:  /perfil/cancelarSolicitudBaja
    defaults: { _controller: ProyectoPrincipalBundle:Perfil:cancelarSolicitudBaja }
    requirements:
      _method: POST

proyecto_principal_acceso:
    pattern:  /acceso
    defaults: { _controller: ProyectoPrincipalBundle:Users:acceso }
proyecto_principal_registro:
    pattern:  /registro
    defaults: { _controller: ProyectoPrincipalBundle:Users:registro }
proyecto_principal_cuenta_guardar:
    pattern:  /cuenta/guardar
    defaults: { _controller: ProyectoPrincipalBundle:Default:cuentaGuardar }
    requirements:
      _method: POST
proyecto_principal_cerrarsesion:
    pattern:  /logout
    defaults: { _controller: ProyectoPrincipalBundle:Default:acceso }
proyecto_principal_perfil:
    pattern:  /perfil
    defaults: { _controller: ProyectoPrincipalBundle:Default:perfil }




proyecto_principal_listado:
    pattern:  /listado
    defaults: { _controller: ProyectoPrincipalBundle:Default:listado }
proyecto_principal_acerca:
    pattern:  /acerca
    defaults: { _controller: ProyectoPrincipalBundle:Default:acerca }
proyecto_principal_validacion:
    pattern:  /validacion
proyecto_principal_nuevo:
    pattern:  /nuevo
    defaults: { _controller: ProyectoPrincipalBundle:Default:nuevo }
proyecto_principal_historia:
    pattern:  /historia
    defaults: { _controller: ProyectoPrincipalBundle:Default:historia }
login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
proyecto_principal_procesa_objeto:
    pattern:  /procesa/objeto
    defaults: { _controller: ProyectoPrincipalBundle:Default:procesaObjeto }
    requirements:
      _method: POST
proyecto_principal_elimina_objeto:
    pattern:  /elimina/
    defaults: { _controller: ProyectoPrincipalBundle:Default:eliminar }
    requirements:
      _method: POST
proyecto_principal_editar_objeto:
    pattern:  /editar/{id}
    defaults: { _controller: ProyectoPrincipalBundle:Default:editar,id: '1' }
proyecto_principal_ver_objeto:
    pattern:  /ver/{id}
    defaults: { _controller: ProyectoPrincipalBundle:Default:ver,id: '1' }

